// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kyber_collection/src/mod_collection.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CollectionModAdapter());
    registerAdapter(ModCollectionMetaDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CollectionModAdapter());
    registerAdapter(ModCollectionMetaDataAdapter());
  }
}
